apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ $.Values.fullnameOverride }}-gsm-store
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "universal-helm.labels" $ | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ $.Values.global.projectID }}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: sa-{{ $.Values.fullnameOverride }}
---

{{- range $chain, $config := $.Values.global.supported_chains }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Values.fullnameOverride }}-{{ $chain }}-{{ $config.chain_id }}-configs
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "universal-helm.labels" $ | nindent 4 }}
spec:
  refreshPolicy: OnChange
  refreshInterval: 168h #  7 days
  secretStoreRef:
    name: {{ $.Values.fullnameOverride }}-gsm-store
    kind: SecretStore
  target:
    name: {{ $.Values.fullnameOverride }}-{{ $chain }}-{{ $config.chain_id }}-configs
    creationPolicy: Owner
  data:
    - secretKey: "{{ $config.chain_id }}.json"
      remoteRef:
        key: {{ $config.gcpsecretkey }}
        version: latest
---
{{- end }}